image: node:9

stages:
  - build
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

before_script:
  - yarn || true # Don't blow up when 'yarn' doesn't exist

install:
  stage: build
  script:
    - echo ðŸ–
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push

storybook:
  stage: build
  script:
    - yarn storybook:build
  artifacts:
    paths:
      - dist-storybook/

release:
  stage: release
  image: kiwicom/s3cmd-plus-docker
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: https://nitro-$CI_COMMIT_REF_SLUG.fe.staging.kiwi.com/nitrolib/
  script:
    - >
      s3cmd sync
      --no-preserve
      --no-mime-magic
      --guess-mime-type
      --default-mime-type="application/json"
      --recursive dist-storybook/*
      s3://frontend-nitro-dev/nitrolib/${CI_COMMIT_REF_SLUG}/
