image: node:9

stages:
  - build
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

before_script:
  - yarn || true # Don't blow up when 'yarn' doesn't exist

install:
  stage: build
  script:
    - echo ðŸ–
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push

build:
  stage: build
  script:
    - yarn bundle
  artifacts:
    paths:
      - data/
      - dist/

test:
  stage: build
  script:
    - yarn test --coverage

lint:
  stage: build
  script:
    - yarn lint

madge:
  stage: build
  script:
    - yarn madge

flow:
  stage: build
  script:
    - yarn flow check

release:
  stage: release
  image: kiwicom/s3cmd-plus-docker
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://nitro-$CI_COMMIT_REF_SLUG.fe.staging.kiwi.com/pages/kiwicom/en/
  script:
    - >
      s3cmd sync
      --no-preserve
      --no-mime-magic
      --guess-mime-type
      --default-mime-type="application/json"
      --recursive dist/static/*
      s3://frontend-nitro-dev/${CI_COMMIT_REF_SLUG}/

storybook:
  stage: release
  script:
    - yarn storybook:build
    - echo "Upload dist/storybook/ to S3 plz"
